### ISSUE TITLE
Cannot find type definition file for 'redux'

### ISSUE THREAD

**Issue by JesseVarGar** [OpenEnergyDashboard/OED#990] opened 2023-08-13 06:54 UTC
### Describe the bug
I came across this bug by chance, not because it was affecting anything. It doesn't appear to do anything except highlight line 1 in tsconfig.json. This is the description that VSC gives me for the red highlight on line 1:

Cannot find type definition file for 'redux'.
The file is in the program because:
Entry point for implicit type library 'redux'

### To Reproduce
1. Go to tsconfig.json file
2. See error on line 1

### Expected behavior
No change in behavior from what I can tell.

### Machine info (please complete the following information)

 - OS: [Windows 11 Home]
 - Browser & Version [Firefox 116.0.2 (64-bit)]
 - OED Version [0.8.0]

**Comment by Airom42** [comment] 2023-08-13 18:12
I've noticed this as well. From my understanding of this error, this is because the `types/redux` folder is added to the typeroots path in tsconfig, but this isn't needed.
Removing the `typeRoots` parameter from tsconfig entirely seems to both fix this issue and produce no errors.

**Comment by spearec** [comment] 2023-08-13 18:21
I've noticed this as well. It seems the issue is caused by including `src/client/app/types/redux` in tsconfig's `typeRoots`, when it's unclear if we need to do so.
Removing the `typeRoots` from tsconfig entirely fixes the issue and seems to cause no other problems, but I don't know if that's a valid fix.

**Comment by huss** [comment] 2023-08-15 17:11
Hi @JesseVarGar. Thanks for reporting this. Would you like to put in a PR to fix this? If not, someone else can do it.

**Comment by JesseVarGar** [comment] 2023-08-17 19:11
I don't have much time right now, but I can try to fix it sometime next week if no one gets to it before me.

**Comment by huss** [comment] 2023-08-25 17:05
The same error showed up while working on PR #919. I applied the proposed fix and it seems to work fine and will be part of that pull request.

**Closed as completed** 2023-08-30 23:57 UTC
