### ISSUE TITLE
Meter list out of order

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#412] opened 2019-04-15 18:11 UTC
When creating a new group, "Mauer 1st" is the first option in the "Select Meters" drop-down panel which is otherwise alphabetical.

**Comment by NoraCodes** [comment] 2019-04-17 15:33
I can't reproduce this:

![Screenshot_2019-04-17_10-19-57](https://user-images.githubusercontent.com/3290365/56300808-36449480-60fc-11e9-9757-d8079d2f994b.png)

**Comment by wendelap** [comment] 2019-04-17 17:38
This only occurs on the "Create a Group" page.

![image](https://user-images.githubusercontent.com/39921639/56308776-b4f5fd80-610d-11e9-9d71-0c245fbd7f49.png)

**Comment by tallulahshepherd** [comment] 2019-05-05 22:03
Looked into this a little, it's only ever Mauer 1st at the top, and it's the only thing that's out of order, as OP says. The code is also exactly the same for sorting the meters in the **CreateGroupContainer** as in the **MeterDropdownContainer**, yet the MeterDropdownContainer works as expected and CreateGroupContainer does _not_. Not able to solve this right now, but hoped my looking into it might help the next person.

**Comment by huss** [comment] 2021-03-02 22:17
It should be determined if this is an ongoing issue and can be reproduced outside this one site to decide if it needs to be addressed.

**Comment by huss** [comment] 2021-11-14 22:37
I tried to recreate this issue but cannot. It might still be around but hard to reproduce. Given the situation, I'm closing this issue. We can reopen if it is ever seen again.

**Closed as completed by huss** 2021-11-14 22:37 UTC
Labels: t-bug, i-good-first-issue
